"use client";

import { useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { useIsDarkMode } from "@/hooks/use-is-dark-mode";

const CODE_LENGTH = 6;

interface OtpPanelProps {
  onBack: () => void;
  onTryAnother: () => void;
}

function OtpDigitInputs({ length, onComplete }: { length: number; onComplete: (complete: boolean) => void }) {
  const isDark = useIsDarkMode();
  const [digits, setDigits] = useState<string[]>(Array(length).fill(""));
  const inputsRef = useRef<(HTMLInputElement | null)[]>([]);

  const setDigit = (index: number, value: string) => {
    const next = [...digits];
    next[index] = value.replace(/\D/g, "").slice(-1);
    setDigits(next);
    onComplete(next.every((d) => d.length === 1));
    if (next[index] && index < length - 1) inputsRef.current[index + 1]?.focus();
  };

  return (
    <div className="flex justify-between gap-2">
      {digits.map((d, i) => (
        <input
          key={i}
          ref={(el) => {
            inputsRef.current[i] = el;
          }}
          value={d}
          onChange={(e) => setDigit(i, e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Backspace" && !d && i > 0) inputsRef.current[i - 1]?.focus();
          }}
          inputMode="numeric"
          maxLength={1}
          aria-label={`Digit ${i + 1}`}
          className={cn(
            "h-14 w-11 rounded-xl text-center text-lg outline-none focus:ring-2 focus:ring-[rgb(100,142,252)]",
            isDark ? "bg-[rgb(42,50,54)] text-[rgb(238,241,243)]" : "bg-[rgb(240,240,240)] text-[rgb(26,26,27)]"
          )}
        />
      ))}
    </div>
  );
}

function PanelShell({
  onBack,
  title,
  description,
  children,
  onTryAnother,
  tryAnotherLabel,
}: {
  onBack: () => void;
  title: string;
  description: string;
  children: React.ReactNode;
  onTryAnother: () => void;
  tryAnotherLabel: string;
}) {
  const isDark = useIsDarkMode();

  return (
    <div className="flex flex-col gap-4">
      <button
        type="button"
        onClick={onBack}
        aria-label="Back"
        className={cn(
          "-ml-2 flex h-8 w-8 items-center justify-center rounded-full",
          isDark ? "text-[rgb(183,202,212)] hover:bg-white/10" : "text-[rgb(87,101,109)] hover:bg-black/5"
        )}
      >
        <svg fill="currentColor" height="20" width="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M17.5 9.1H4.679l5.487-5.462a.898.898 0 00.003-1.272.898.898 0 00-1.272-.003l-7.032 7a.898.898 0 000 1.275l7.03 7a.896.896 0 001.273-.003.898.898 0 00-.002-1.272l-5.487-5.462h12.82a.9.9 0 000-1.8Z" />
        </svg>
      </button>
      <h2 className={cn("text-xl font-bold leading-6", isDark ? "text-[rgb(238,241,243)]" : "text-[rgb(26,26,27)]")}>{title}</h2>
      <p className={cn("text-sm", isDark ? "text-[rgb(183,202,212)]" : "text-[rgb(87,101,109)]")}>{description}</p>
      {children}
      <button
        type="button"
        onClick={onTryAnother}
        className="self-start text-sm font-medium text-[rgb(100,142,252)] hover:underline"
      >
        {tryAnotherLabel}
      </button>
    </div>
  );
}

export function OtpAppPanel({ onBack, onTryAnother }: OtpPanelProps) {
  const isDark = useIsDarkMode();
  const [complete, setComplete] = useState(false);

  return (
    <PanelShell
      onBack={onBack}
      onTryAnother={onTryAnother}
      title="Enter your code"
      description="Enter the 6-digit code generated by your authenticator app."
      tryAnotherLabel="Try another way"
    >
      <form className="flex flex-col gap-4" onSubmit={(e) => e.preventDefault()}>
        <OtpDigitInputs length={CODE_LENGTH} onComplete={setComplete} />
        <button
          type="submit"
          disabled={!complete}
          className={cn(
            "h-12 w-full rounded-full text-sm font-semibold transition-colors",
            complete
              ? "cursor-pointer bg-[rgb(100,142,252)] text-[rgb(238,241,243)]"
              : isDark
                ? "cursor-not-allowed bg-white/[0.047] text-white/[0.247]"
                : "cursor-not-allowed bg-black/[0.05] text-black/[0.25]"
          )}
        >
          Continue
        </button>
      </form>
    </PanelShell>
  );
}

export function OtpBackupPanel({ onBack, onTryAnother }: OtpPanelProps) {
  const isDark = useIsDarkMode();
  const [code, setCode] = useState("");

  return (
    <PanelShell
      onBack={onBack}
      onTryAnother={onTryAnother}
      title="Enter a backup code"
      description="Enter one of the backup codes you saved when you set up two-factor authentication."
      tryAnotherLabel="Use authenticator app instead"
    >
      <form className="flex flex-col gap-4" onSubmit={(e) => e.preventDefault()}>
        <input
          value={code}
          onChange={(e) => setCode(e.target.value)}
          placeholder="Backup code"
          aria-label="Backup code"
          className={cn(
            "h-14 rounded-[20px] px-4 text-base outline-none",
            isDark
              ? "bg-[rgb(42,50,54)] text-[rgb(238,241,243)] placeholder:text-[rgb(139,162,173)]"
              : "bg-[rgb(240,240,240)] text-[rgb(26,26,27)] placeholder:text-[rgb(120,124,126)]"
          )}
        />
        <button
          type="submit"
          disabled={code.length === 0}
          className={cn(
            "h-12 w-full rounded-full text-sm font-semibold transition-colors",
            code.length > 0
              ? "cursor-pointer bg-[rgb(100,142,252)] text-[rgb(238,241,243)]"
              : isDark
                ? "cursor-not-allowed bg-white/[0.047] text-white/[0.247]"
                : "cursor-not-allowed bg-black/[0.05] text-black/[0.25]"
          )}
        >
          Continue
        </button>
      </form>
    </PanelShell>
  );
}
