"use client";

import { useRef, useState } from "react";
import { cn } from "@/lib/utils";

const CODE_LENGTH = 6;

interface OtpPanelProps {
  onBack: () => void;
  onTryAnother: () => void;
}

function OtpDigitInputs({ length, onComplete }: { length: number; onComplete: (complete: boolean) => void }) {
  const [digits, setDigits] = useState<string[]>(Array(length).fill(""));
  const inputsRef = useRef<(HTMLInputElement | null)[]>([]);

  const setDigit = (index: number, value: string) => {
    const next = [...digits];
    next[index] = value.replace(/\D/g, "").slice(-1);
    setDigits(next);
    onComplete(next.every((d) => d.length === 1));
    if (next[index] && index < length - 1) inputsRef.current[index + 1]?.focus();
  };

  return (
    <div className="flex justify-between gap-2">
      {digits.map((d, i) => (
        <input
          key={i}
          ref={(el) => {
            inputsRef.current[i] = el;
          }}
          value={d}
          onChange={(e) => setDigit(i, e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Backspace" && !d && i > 0) inputsRef.current[i - 1]?.focus();
          }}
          inputMode="numeric"
          maxLength={1}
          aria-label={`Digit ${i + 1}`}
          className="h-14 w-11 rounded-xl bg-[rgb(42,50,54)] text-center text-lg text-[rgb(238,241,243)] outline-none focus:ring-2 focus:ring-[rgb(100,142,252)]"
        />
      ))}
    </div>
  );
}

function PanelShell({
  onBack,
  title,
  description,
  children,
  onTryAnother,
  tryAnotherLabel,
}: {
  onBack: () => void;
  title: string;
  description: string;
  children: React.ReactNode;
  onTryAnother: () => void;
  tryAnotherLabel: string;
}) {
  return (
    <div className="flex flex-col gap-4">
      <button
        type="button"
        onClick={onBack}
        aria-label="Back"
        className="-ml-2 flex h-8 w-8 items-center justify-center rounded-full text-[rgb(183,202,212)] hover:bg-white/10"
      >
        <svg fill="currentColor" height="20" width="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M17.5 9.1H4.679l5.487-5.462a.898.898 0 00.003-1.272.898.898 0 00-1.272-.003l-7.032 7a.898.898 0 000 1.275l7.03 7a.896.896 0 001.273-.003.898.898 0 00-.002-1.272l-5.487-5.462h12.82a.9.9 0 000-1.8Z" />
        </svg>
      </button>
      <h2 className="text-xl font-bold leading-6 text-[rgb(238,241,243)]">{title}</h2>
      <p className="text-sm text-[rgb(183,202,212)]">{description}</p>
      {children}
      <button
        type="button"
        onClick={onTryAnother}
        className="self-start text-sm font-medium text-[rgb(100,142,252)] hover:underline"
      >
        {tryAnotherLabel}
      </button>
    </div>
  );
}

export function OtpAppPanel({ onBack, onTryAnother }: OtpPanelProps) {
  const [complete, setComplete] = useState(false);

  return (
    <PanelShell
      onBack={onBack}
      onTryAnother={onTryAnother}
      title="Enter your code"
      description="Enter the 6-digit code generated by your authenticator app."
      tryAnotherLabel="Try another way"
    >
      <form className="flex flex-col gap-4" onSubmit={(e) => e.preventDefault()}>
        <OtpDigitInputs length={CODE_LENGTH} onComplete={setComplete} />
        <button
          type="submit"
          disabled={!complete}
          className={cn(
            "h-12 w-full rounded-full text-sm font-semibold transition-colors",
            complete
              ? "cursor-pointer bg-[rgb(100,142,252)] text-[rgb(238,241,243)]"
              : "cursor-not-allowed bg-white/[0.047] text-white/[0.247]"
          )}
        >
          Continue
        </button>
      </form>
    </PanelShell>
  );
}

export function OtpBackupPanel({ onBack, onTryAnother }: OtpPanelProps) {
  const [code, setCode] = useState("");

  return (
    <PanelShell
      onBack={onBack}
      onTryAnother={onTryAnother}
      title="Enter a backup code"
      description="Enter one of the backup codes you saved when you set up two-factor authentication."
      tryAnotherLabel="Use authenticator app instead"
    >
      <form className="flex flex-col gap-4" onSubmit={(e) => e.preventDefault()}>
        <input
          value={code}
          onChange={(e) => setCode(e.target.value)}
          placeholder="Backup code"
          aria-label="Backup code"
          className="h-14 rounded-[20px] bg-[rgb(42,50,54)] px-4 text-base text-[rgb(238,241,243)] outline-none placeholder:text-[rgb(139,162,173)]"
        />
        <button
          type="submit"
          disabled={code.length === 0}
          className={cn(
            "h-12 w-full rounded-full text-sm font-semibold transition-colors",
            code.length > 0
              ? "cursor-pointer bg-[rgb(100,142,252)] text-[rgb(238,241,243)]"
              : "cursor-not-allowed bg-white/[0.047] text-white/[0.247]"
          )}
        >
          Continue
        </button>
      </form>
    </PanelShell>
  );
}
